import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { CredentialSetup } from '../CredentialSetup'

const command = vi.hoisted(() => vi.fn())
vi.mock('@/services/engines', () => ({ engineCommand: command }))
afterEach(cleanup)
beforeEach(() => command.mockReset())
describe('secure storage intake', () => {
  it('uses an existing provider without offering installation', async () => {
    command.mockResolvedValue({ ready: true, platform: 'linux', can_install: false })
    const ready = vi.fn()
    render(<CredentialSetup onReady={ready} />)
    await screen.findByText('Secure credential storage is ready for LAN pairing.')
    expect(screen.queryByRole('button', { name: 'Set up secure storage' })).not.toBeInTheDocument()
    expect(ready).toHaveBeenLastCalledWith(true)
    expect(command).toHaveBeenCalledTimes(1)
  })
  it('installs only after a click and rechecks instead of assuming success', async () => {
    command.mockResolvedValue({ ready: false, platform: 'linux', can_install: true })
    const ready = vi.fn()
    render(<CredentialSetup onReady={ready} />)
    await screen.findByRole('alert')
    expect(command).not.toHaveBeenCalledWith('credential_install', expect.anything())
    command.mockImplementation(async (action: string) => action === 'credential_install' ? { installed: true } : { ready: true, platform: 'linux', can_install: false })
    fireEvent.click(screen.getByRole('button', { name: 'Set up secure storage' }))
    await screen.findByText('Secure credential storage is ready for LAN pairing.')
    expect(command).toHaveBeenCalledWith('credential_install', { confirmed: true })
    expect(screen.getByText('Secure credential storage is ready for LAN pairing.')).toBeInTheDocument()
    expect(ready).toHaveBeenLastCalledWith(true)
  })
  it('supports skip and manual unlock guidance without enabling pairing', async () => {
    command.mockResolvedValue({ ready: false, platform: 'linux', can_install: false, error: 'locked' })
    const ready = vi.fn()
    render(<CredentialSetup onReady={ready} />)
    await screen.findByRole('alert')
    fireEvent.click(screen.getByRole('button', { name: 'Skip for now' }))
    expect(screen.getByText(/Local models remain available/)).toBeInTheDocument()
    expect(ready).not.toHaveBeenCalledWith(true)
    fireEvent.click(screen.getByRole('button', { name: 'Set up secure storage' }))
    fireEvent.click(screen.getByRole('button', { name: 'Set up secure storage' }))
    expect(screen.getByText(/On Linux, open your system software manager/)).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Check again' }))
    await waitFor(() => expect(command).toHaveBeenCalledTimes(2))
  })
  it('keeps pairing unavailable after installation if the keyring still needs unlocking', async () => {
    command.mockResolvedValue({ ready: false, platform: 'linux', can_install: true })
    const ready = vi.fn()
    render(<CredentialSetup onReady={ready} />)
    await screen.findByRole('alert')
    fireEvent.click(screen.getByRole('button', { name: 'Set up secure storage' }))
    await screen.findByText(/Installation finished/)
    expect(screen.getByText(/Secure storage is unavailable/)).toBeInTheDocument()
    await waitFor(() => expect(command).toHaveBeenCalledTimes(3))
    expect(ready).not.toHaveBeenCalledWith(true)
  })
  it('shows an installation cancellation and permits retry', async () => {
    command.mockResolvedValue({ ready: false, platform: 'linux', can_install: true })
    render(<CredentialSetup />)
    await screen.findByRole('alert')
    command.mockRejectedValueOnce(new Error('Administrator approval cancelled'))
    fireEvent.click(screen.getByRole('button', { name: 'Set up secure storage' }))
    await screen.findByText(/Administrator approval cancelled/)
    expect(screen.getByRole('button', { name: 'Check again' })).toBeEnabled()
  })
})
