import { SessionInfo, UnloadResult, GinferConfig, GinferBenchmarkRequest, GinferBenchmarkResult } from './types';
export declare function normalizeGinferConfig(config: any): GinferConfig;
export declare function loadGinferModel(binaryPath: string, hostDirectory: string, modelId: string, modelPath: string, cfg: GinferConfig, isEmbedding?: boolean, timeout?: number): Promise<SessionInfo>;
export declare function unloadGinferModel(pid: number): Promise<UnloadResult>;
export declare function isProcessRunning(pid: number): Promise<boolean>;
export declare function findSessionByModel(modelId: string): Promise<SessionInfo | null>;
export declare function getLoadedModels(): Promise<string[]>;
export declare function getAllSessions(): Promise<SessionInfo[]>;
export declare function runGinferBenchmark(request: GinferBenchmarkRequest): Promise<GinferBenchmarkResult>;
export declare function cancelGinferBenchmark(runId: string): Promise<boolean>;
export declare function cleanupGinferProcesses(): Promise<void>;
export * from './types';
